name: Compile with SourceMod

on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - steam.png
      - .gitignore
      - .github/FUNDING.yml
      - .archive/**
      - accelerator.smx
      - accelerator.sp
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - steam.png
      - .gitignore
      - .github/FUNDING.yml
      - .archive/**
      - accelerator.smx
      - accelerator.sp
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.13.x'
          version-file: ./discord_redux.sp

      - name: Create include directory
        run: mkdir -p include

      - name: Download Third-Party Includes
        working-directory: include
        run: |
          mkdir -p ripext multicolors
          wget -q -L https://raw.githubusercontent.com/ProjectSky/sm-ext-discord/refs/heads/main/scripting/include/discord.inc -O discord.inc
          wget -q -L https://raw.githubusercontent.com/irql-notlessorequal/SteamWorks/refs/heads/x64/Pawn/includes/SteamWorks.inc -O SteamWorks.inc
          wget -q -L https://raw.githubusercontent.com/srcdslab/sm-ext-ripext/refs/heads/main/pawn/scripting/include/ripext.inc -O ripext.inc
          wget -q -L https://raw.githubusercontent.com/srcdslab/sm-ext-ripext/refs/heads/main/pawn/scripting/include/ripext/http.inc -O ripext/http.inc
          wget -q -L https://raw.githubusercontent.com/srcdslab/sm-ext-ripext/refs/heads/main/pawn/scripting/include/ripext/json.inc -O ripext/json.inc
          wget -q -L https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/multicolors.inc -O multicolors.inc
          wget -q -L https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/multicolors/colors.inc -O multicolors/colors.inc
          wget -q -L https://raw.githubusercontent.com/JoinedSenses/SourceMod-IncludeLibrary/master/include/multicolors/morecolors.inc -O multicolors/morecolors.inc
          wget -q -L https://raw.githubusercontent.com/asherkin/accelerator/refs/heads/master/scripting/include/accelerator.inc -O accelerator.inc
          wget -q -L https://raw.githubusercontent.com/saxybois/sm-maprate/refs/heads/main/maprate.inc -O maprate.inc
          wget -q -L https://raw.githubusercontent.com/Phil25/RTD/refs/heads/master/scripting/include/rtd2.inc -O rtd2.inc
          ls -lah

      - name: Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Compile plugins
        run: |
          for file in discord_redux.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -w234 -O2 -v2 -i include $file --warning=203
          done
          echo "===OUT FILES==="
          ls
          echo version = ${{ steps.setup_sp.outputs.plugin-version }}
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Move smx to plugins directory
        run: |
          mkdir -p plugins
          mv discord_redux.smx plugins/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Discord Redux (${{ env.COMMIT_SHA }})"
          path: |
            plugins/discord_redux.smx
            translations/**